package projectx.entidad;
// Generated 03-ene-2022 14:04:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

    private String codDepto;
    private String nomDepto;
    private String ciudad;
    private Set empleados = new HashSet(0);
    private Set proyectos = new HashSet(0);

    public Departamento() {
    }

    public Departamento(String codDepto) {
        this.codDepto = codDepto;
    }

    public Departamento(String codDepto, String nomDepto, String ciudad, Set empleados, Set proyectos) {
        this.codDepto = codDepto;
        this.nomDepto = nomDepto;
        this.ciudad = ciudad;
        this.empleados = empleados;
        this.proyectos = proyectos;
    }

    public String getCodDepto() {
        return this.codDepto;
    }

    public void setCodDepto(String codDepto) {
        this.codDepto = codDepto;
    }

    public String getNomDepto() {
        return this.nomDepto;
    }

    public void setNomDepto(String nomDepto) {
        this.nomDepto = nomDepto;
    }

    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public Set getEmpleados() {
        return this.empleados;
    }

    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }

    public Set getProyectos() {
        return this.proyectos;
    }

    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }

    @Override
    public String toString() {
        //return "Departamento{" + "codDepto=" + codDepto + ", nomDepto=" + nomDepto + ", ciudad=" + ciudad + '}';
        return codDepto;
    }

}
