package projectx.entidad;
// Generated 03-ene-2022 14:04:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private String codPro;
     private Departamento departamento;
     private String nomPro;
     private Set trabajas = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(String codPro) {
        this.codPro = codPro;
    }
    public Proyecto(String codPro, Departamento departamento, String nomPro, Set trabajas) {
       this.codPro = codPro;
       this.departamento = departamento;
       this.nomPro = nomPro;
       this.trabajas = trabajas;
    }
   
    public String getCodPro() {
        return this.codPro;
    }
    
    public void setCodPro(String codPro) {
        this.codPro = codPro;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNomPro() {
        return this.nomPro;
    }
    
    public void setNomPro(String nomPro) {
        this.nomPro = nomPro;
    }
    public Set getTrabajas() {
        return this.trabajas;
    }
    
    public void setTrabajas(Set trabajas) {
        this.trabajas = trabajas;
    }




}


