package projectx.entidad;
// Generated 03-ene-2022 14:04:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String codEmp;
     private Departamento departamento;
//     private String codDepto;
     private Empleado empleado;
     private String nomEmp;
     private Date fechaIngreso;
     private Float salario;
     private Set empleados = new HashSet(0);
     private Set trabajas = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String codEmp) {
        this.codEmp = codEmp;
    }
    public Empleado(String codEmp, Departamento departamento, Empleado empleado, String nomEmp, Date fechaIngreso, Float salario, Set empleados, Set trabajas) {
       this.codEmp = codEmp;
       this.departamento = departamento;
       this.empleado = empleado;
       this.nomEmp = nomEmp;
       this.fechaIngreso = fechaIngreso;
       this.salario = salario;
       this.empleados = empleados;
       this.trabajas = trabajas;
    }

   
    public String getCodEmp() {
        return this.codEmp;
    }
    
    public void setCodEmp(String codEmp) {
        this.codEmp = codEmp;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getTrabajas() {
        return this.trabajas;
    }
    
    public void setTrabajas(Set trabajas) {
        this.trabajas = trabajas;
    }

    @Override
    public String toString() {
        //return "Empleado{" + "codEmp=" + codEmp + ", nomEmp=" + nomEmp + ", fechaIngreso=" + fechaIngreso + ", salario=" + salario + ", trabajas=" + trabajas + '}';
        return codEmp;
    }




}


