package projectx.entidad;
// Generated 03-ene-2022 14:04:21 by Hibernate Tools 4.3.1



/**
 * TrabajaId generated by hbm2java
 */
public class TrabajaId  implements java.io.Serializable {


     private String codEmp;
     private String codPro;

    public TrabajaId() {
    }

    public TrabajaId(String codEmp, String codPro) {
       this.codEmp = codEmp;
       this.codPro = codPro;
    }
   
    public String getCodEmp() {
        return this.codEmp;
    }
    
    public void setCodEmp(String codEmp) {
        this.codEmp = codEmp;
    }
    public String getCodPro() {
        return this.codPro;
    }
    
    public void setCodPro(String codPro) {
        this.codPro = codPro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrabajaId) ) return false;
		 TrabajaId castOther = ( TrabajaId ) other; 
         
		 return ( (this.getCodEmp()==castOther.getCodEmp()) || ( this.getCodEmp()!=null && castOther.getCodEmp()!=null && this.getCodEmp().equals(castOther.getCodEmp()) ) )
 && ( (this.getCodPro()==castOther.getCodPro()) || ( this.getCodPro()!=null && castOther.getCodPro()!=null && this.getCodPro().equals(castOther.getCodPro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodEmp() == null ? 0 : this.getCodEmp().hashCode() );
         result = 37 * result + ( getCodPro() == null ? 0 : this.getCodPro().hashCode() );
         return result;
   }   


}


