/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADTarea5;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.xmldb.api.DatabaseManager;
import org.xmldb.api.base.Collection;
import org.xmldb.api.base.Database;
import org.xmldb.api.base.Resource;
import org.xmldb.api.base.ResourceIterator;
import org.xmldb.api.base.ResourceSet;
import org.xmldb.api.base.XMLDBException;
import org.xmldb.api.modules.XPathQueryService;

/**
 *
 * @author Administrador
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Panel() {
        this.setTitle("AD UD5 Tarea Online JEJM");
        //this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnImprimir1 = new javax.swing.JButton();
        btnImprimir2 = new javax.swing.JButton();
        btnImprimir3 = new javax.swing.JButton();
        btnImprimir4 = new javax.swing.JButton();
        btnImprimir5 = new javax.swing.JButton();
        btnImprimir6 = new javax.swing.JButton();
        btnImprimir7 = new javax.swing.JButton();
        btnListarBiblioteca = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnListarLibros = new javax.swing.JButton();
        btnListarAutores = new javax.swing.JButton();
        btnListarPrestamos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnImprimir.setText("1. Título de los Libros Publicados en 2002 Ordenados Alfabéticamente");
        btnImprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnImprimir1.setText("2. Título de los libros que posean más de 1 autor");
        btnImprimir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });

        btnImprimir2.setText("3. Título, primer autor y páginas de los libros prestados");
        btnImprimir2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir2ActionPerformed(evt);
            }
        });

        btnImprimir3.setText("4. Nombre de cada lector y suma total de páginas de libros que le han prestado");
        btnImprimir3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir3ActionPerformed(evt);
            }
        });

        btnImprimir4.setText("5. Insertar el nodo evaluacion y cuyo contenido sea 10 como último nodo en la publicacion=2007");
        btnImprimir4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir4ActionPerformed(evt);
            }
        });

        btnImprimir5.setText("6. Sustituir el valor del nodo paginas con 700 en la publicacion=2005");
        btnImprimir5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir5ActionPerformed(evt);
            }
        });

        btnImprimir6.setText("7. Modificar el nombre del nodo inicio de cada documento de la colección Prestamos por fechainicio.");
        btnImprimir6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir6ActionPerformed(evt);
            }
        });

        btnImprimir7.setText("8. Eliminar el nodo direccion de la tabla Prestamos.");
        btnImprimir7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir7ActionPerformed(evt);
            }
        });

        btnListarBiblioteca.setText("Listar Biblioteca");
        btnListarBiblioteca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarBibliotecaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnListarLibros.setText("Listar Libros");
        btnListarLibros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLibrosActionPerformed(evt);
            }
        });

        btnListarAutores.setText("Listar Autores");
        btnListarAutores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListarAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAutoresActionPerformed(evt);
            }
        });

        btnListarPrestamos.setText("Listar Prestamos");
        btnListarPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPrestamosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("AD UD5 Tarea Online JEJM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnImprimir7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListarPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnListarBiblioteca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir1)
                    .addComponent(btnListarLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir2)
                    .addComponent(btnListarAutores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir3)
                    .addComponent(btnListarPrestamos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir4)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void imprimirPantalla(ResourceSet result) throws XMLDBException {
        txtArea.setText("");// Limpia la pantalla
        ResourceIterator i = result.getIterator();
        while (i.hasMoreResources()) { //Procesamos el resultado
            Resource r = i.nextResource();
            String cadena = (String) r.getContent();
            txtArea.append(cadena + "\n");

        }
    }

    public void imprimirTest(ResourceSet result) {
        ResourceIterator i = null;
        try {
            i = result.getIterator();
        } catch (XMLDBException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while (i.hasMoreResources()) { //Procesamos el resultado
                Resource r = i.nextResource();
                String cadena = (String) r.getContent();
                txtArea.append(cadena);
            }
        } catch (XMLDBException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        try {
            //imprimirPantalla(Metodos.consulta0());
            imprimirPantalla(Metodos.leerFichero1());
        } catch (XMLDBException | ClassNotFoundException | InstantiationException | IllegalAccessException | IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
        try {
            //imprimirPantalla(Metodos.consulta2());
            imprimirPantalla(Metodos.leerFichero2());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException | IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnImprimir1ActionPerformed

    private void btnImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir2ActionPerformed
        try {
            //imprimirPantalla(Metodos.consulta2());
            imprimirPantalla(Metodos.leerFichero3());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException | IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimir2ActionPerformed

    private void btnImprimir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir3ActionPerformed
        try {
            //imprimirPantalla(Metodos.consulta4());
            imprimirPantalla(Metodos.leerFichero4());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException | IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimir3ActionPerformed

    private void btnImprimir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir4ActionPerformed
        try {
            //imprimirPantalla(Metodos.consulta5());
            imprimirPantalla(Metodos.leerFichero5());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException | IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Nodo Actualizado Correctamente ", " Nodo Actualizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnImprimir4ActionPerformed

    private void btnImprimir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir5ActionPerformed
        try {
            //imprimirPantalla(Metodos.consulta6());
            imprimirPantalla(Metodos.leerFichero6());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException | IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Nodo Actualizado Correctamente ", " Nodo Actualizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnImprimir5ActionPerformed

    private void btnImprimir6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir6ActionPerformed
        try {
            //imprimirPantalla(Metodos.consulta7());
            imprimirPantalla(Metodos.leerFichero7());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException | IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Nodo Actualizado Correctamente ", " Nodo Actualizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnImprimir6ActionPerformed

    private void btnImprimir7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir7ActionPerformed
        try {
            //imprimirPantalla(Metodos.consulta8());
            imprimirPantalla(Metodos.leerFichero8());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException | IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Nodo Actualizado Correctamente ", " Nodo Actualizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnImprimir7ActionPerformed

    private void btnListarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarBibliotecaActionPerformed
        try {
            imprimirPantalla(Metodos.consulta0());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarBibliotecaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿ Desea salir de la aplicación ?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {


            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnListarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLibrosActionPerformed
        try {
            imprimirPantalla(Metodos.consultaLibros());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarLibrosActionPerformed

    private void btnListarAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAutoresActionPerformed
        try {
            imprimirPantalla(Metodos.consultaAutores());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarAutoresActionPerformed

    private void btnListarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPrestamosActionPerformed
        try {
            imprimirPantalla(Metodos.consultaPrestamos());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | XMLDBException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnImprimir2;
    private javax.swing.JButton btnImprimir3;
    private javax.swing.JButton btnImprimir4;
    private javax.swing.JButton btnImprimir5;
    private javax.swing.JButton btnImprimir6;
    private javax.swing.JButton btnImprimir7;
    private javax.swing.JButton btnListarAutores;
    private javax.swing.JButton btnListarBiblioteca;
    private javax.swing.JButton btnListarLibros;
    private javax.swing.JButton btnListarPrestamos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
